name: "go-base-service"
logger:
    appname: "go-base-service"
    build: "dev"
    level: "debug" # info/error
controller:
    name: "http"
    http:
        port: 8080
        ginmode: "release"
        readtimeoutmillis: 500
        writetimeoutmillis: 500
        ping: {}
service:
    ping: {}
repository:
    name: "redis"
    redis: {}